# Generated by Django 5.1 on 2024-08-17 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='age',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctor',
            name='gender',
            field=models.CharField(choices=[('M', 'Mujer'), ('H', 'Hombre')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='dueño',
            name='age',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dueño',
            name='gender',
            field=models.CharField(choices=[('M', 'Mujer'), ('H', 'Hombre')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='mascota',
            name='type',
            field=models.CharField(choices=[('CAT', 'Gato'), ('DOG', 'Perro'), ('PRT', 'Loro'), ('TRL', 'Tortuga'), ('Ot', 'Otro animal')], default='', max_length=45),
        ),
    ]
